apiVersion: apps/v1                   #DEPLOYMENT
kind: Deployment
metadata:
  name: mongo-deployment
  labels:                             #labels are for pods many replica which would map to one label
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:                      #match the deployment to the service
      app: mongo
  template:                           #it is the configuration of the pod
    metadata:
      labels:
        app: mongo
    spec:                   
      containers:
      - name: mongodb
        image: mongo:5.0                    #this is a docker image 
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service                 #should me same as the config data 
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017